arc-controller:
  namespace: arc-system

  replicaCount: 3

  serviceAccount:
    name: gha-rs-controller

  flags:
    updateStrategy: "eventual"

arc-runner:
  namespace: arc-runners

  githubConfigUrl: "https://github.com/acesso-io/go"

  githubConfigSecret: pre-defined-secret

  controllerServiceAccount:
    namespace: arc-system
    name: gha-rs-controller

  runnerScaleSetName: "arc-runner"

arc-dind:
  namespace: arc-runners

  githubConfigUrl: "https://github.com/acesso-io/go"

  githubConfigSecret: pre-defined-secret

  containerMode:
    type: "dind"

  controllerServiceAccount:
    namespace: arc-system
    name: gha-rs-controller

  runnerScaleSetName: "arc-dind"
